- name: Hello World Sample
  hosts: all
  vars_prompt:

    - name: url
      prompt: what is the requested url for this VIP?
      private: no
      
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
    - name: print url
      debug:
        var: "{{ url }}"
